name: Publish multiarch postgres-operator image on docker

on:
  push:
    branches:
      - 'v1.10-syzh-arm'
jobs:
  publish:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.19.8"

      # 暂时屏蔽test过程
      #- name: Run unit tests
      #  run: make deps mocks test

      - name: Define image name
        id: image
        run: |
            IMAGE="cdmikechen/postgres-operator:v1.10-arm"
            echo "NAME=$IMAGE" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DOCKER
        uses: docker/login-action@v2
        with:
          # not email
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # https://docs.docker.com/docker-hub/access-tokens/
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multiarch image to docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          push: true
          build-args: BASE_IMAGE=alpine:3.15
          tags: "${{ steps.image.outputs.NAME }}"
          platforms: linux/amd64,linux/arm64
